project:
  type: website

website:
  title: "Jason Smith"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    search: true
    background: dark
    tools:
      - icon: bluesky
        href: https://bsky.app
 






format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



