project:
  type: website
  output-dir: gh-pages


website:
  title: "Jason Smith"
  site-url: "https://www.jasonasmith.net"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    search: true
    background: dark
    tools:
      - icon: bluesky
        href: https://bsky.app
 






format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



