project:
  type: website
  output-dir: gh-pages


website:
  title: "Jason Smith"
  site-url: "https://www.jasonasmith.net"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
    search: true
    tools:
      - icon: bluesky
        href: https://bsky.app
 
format:
  html:
    theme:
      - litera
      - custom.scss
    
    toc: true
    mainfont: "Source Serif 4"
    include-in-header:
      text: 
        <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">



