---
title: "About"
format:
    html:
        toc: true
        toc-location: right

---
Jason Smith is a Professor of Public Health at California State University, Fullerton.  He has served in senior academic leadership roles at CSUF and CSU East Bay, including Dean of the College of Health and Human Development at CSUF and Chair of the Department of Public Health at CSU East Bay, and completed an American Council on Education Fellowship in the Office of Chancellor Cindy Larive at UC Santa Cruz. He has held teaching appointments at the University of Connecticut Health Center and Northeastern University School of Law. Professor Smith's current scholarship examines public health law and climate governance, with a focus on constitutional frameworks for intergenerational justice and the legal status of population health as a norm. His work has appeared in leading law and public health journals, and he serves on the Board of Directors of the American Society of Law, Medicine, and Ethics. He is a licensed attorney in California and Massachusetts. He holds a JD from Northeastern University School of Law and an MTS from Harvard University.

# Education
Juris Doctor • Northeastern University School of Law, Boston, MA • 2003

Master of Theological Studies • Harvard University, Cambridge, MA • 1998

Bachelor of Arts, cum laude, Phi Beta Kappa • University of Tulsa, OK • 1995

# Appointments

Professor, Department of Public Health, California State University, Fullerton • 2024–present

Associate Professor, Department of Public Health, California State University, East Bay • 2019 - 2022

Assistant Professor, Department of Public Health, California State University, East Bay • 2013 - 2019

Assistant Professor, Division of Public Health Law and Bioethics, Univeresity of Connecticut Health Center • 2008 - 2012

