---
title: "Publications and Projects"
format:
    html:
        toc: true
        toc-location: right

---
# Current Projects

## Public Health, Climate Governance, and the Anthropocene 

Smith, Jason A., and Goldberg, Daniel. "A Planetary Health Ethics as a Collection of Governance Problems: Law & Public Health in the Anthropocene" - draft manuscript in progress. (2026)

Smith, Jason A. “Public Health, Governance, and the Anthropocene.” Hous. J. Health L. & Pol’y 18 (2018): 169.

## Climate Change and Public Health Law

Michael T. Schmeltz, Jason A. Smith, Isabella Olmos, Erin Quintero, “Extreme Heat Governance: A Critical Analysis of Heat Action Plans in California”, American Journal of Public Health 113, no. 1 (January 1, 2023): pp. 15-19.

Editor, Special Issue of Journal of Law, Medicine and Ethics on Climate Change, Human Health, Law and Ethics.  January 2021.

Ganesh C, Schmeltz M, Smith J. Introduction Climate Change and the Legal, Ethical, and Health Issues Facing Healthcare and Public Health Systems. The Journal of Law, Medicine & Ethics. 2020;48(4):636-642.

Smith, J., and C. Ganesh. "Disease Surveillance." Chap. 5 In Climate Change, Public Health, and the Law, edited by M. Burger and J. Gundlach. Cambridge: Cambridge University Press, 2018.

Ganesh, C., and J. A. Smith. "Climate Change, Public Health, and Policy: A California Case Study." Am J Public Health (Oct 26 2017): e1-e6.

Smith, Jason A., Jason Vargo, and Sara Pollock Hoverter. "Climate Change and Public Health Policy." The Journal of Law, Medicine & Ethics 45, no. 1_suppl (2017): 82-85

# Prior Work / Scholarship

## First Amendment

Parmet, Wendy E. and Smith, Jason A., Free Speech and Public Health: Unraveling the Commercial-Professional Speech Paradox (2017). Ohio State Law Journal, Vol. 78, No. 4, pp. 887-915 (2017)

Parmet, W. E., Smith, J. A., & Miller, M. J. (2017). Physicians, Firearms, and Free Speech — Overturning Florida’s Firearm-Safety Gag Rule. New England Journal of Medicine. http://doi.org/10.1056/NEJMp1702516

Parmet, W. E., Smith, J. A., & Miller, M. J. (2016). Wollschlaeger v. Governor of Florida — The First Amendment, Physician Speech, and Firearm Safety. New England Journal of Medicine. http://doi.org/10.1056/NEJMp1605740

Parmet, W. E., & Smith, J. A. (2006). Free Speech and Public Health: A Population-Based Approach to the First Amendment. Loyola of Los Angeles Law Review, 39(1), 363-446.

## Food, Obesity, and Public Health Law

Alderman, J., Smith, J. A., Fried, E. J., & Daynard, R. A. (2007). Application of law to the childhood obesity epidemic. The Journal of law, medicine & ethics : a journal of the American Society of Law, Medicine & Ethics, 35, 90-112.

Kelley, B., & Smith, J. A. (2004). Legal approaches to the obesity epidemic: an introduction. Journal of public health policy, 25, 346-352.

Weiss, R. I., Hayne, C. L., & Smith, J. A. (2004). Legislative Approaches to the Obesity Epidemic. J Public Health Pol, 25(3/4), 379-390.

Smith, J. A. (2006). Setting the Stage for Public Health: The Role of Litigation in Controlling Obesity. University of Arkansas Little Rock Law Review, 28, 443.

## Public Health Law

Smith, J. “Law as a social determinant of health.” Chap. 17 in Public Health Law: Concepts and Case Studies, edited by Montrece McNeill Ransom and Laura Magaña Valladares. Springer Publishing, 2021.

Mukherjea A, Ali S, Smith JA. A Human Rights Perspective on Palliative Care: Unraveling Disparities and Determinants among Asian American Populations. Topics in Language Disorders. 2020.

Parmet, Wendy E., Micah L. Berman, and Jason A. Smith. "The Supreme Court’s Crisis Pregnancy Center Case — Implications for Health Law." New England Journal of Medicine 379, no. 16 (2018): 1489-91. https://doi.org/10.1056/NEJMp1809488.

Stanton, Michael V., and Jason A. Smith. "Law, Stigma, and Meaning: Implications for Obesity and HIV Prevention." The Journal of Law, Medicine & Ethics 45, no. 4 (2017): 492-501.

## Pedagogy

Smith, J. A. "Keith Haring, Felix Gonzalez-Torres, Wolfgang Tillmans, and the AIDS Epidemic: The Use of Visual Art in a Health Humanities Course." J Med Humanities  (Feb 23 2018).

Ganesh, C., & Smith, J. (2017). Using Multiple High-Impact Practices to Reduce Bottlenecks and Improve Student Learning in an Undergraduate Health Science Program. Journal of the Scholarship of Teaching and Learning, 17(2), 74-84. 

Smith, J. A. (2008). Training Individuals in Public Health Law. The Journal of law, medicine & ethics : a journal of the American Society of Law, Medicine & Ethics, 36, 50-60.

## Reports and Other Publications

Lazzarini, Z., Case, P., Smith, J. A., (2011). An Evaluation of the Open Society Institute’s Law and Health Initiative. (Unpublished).

Miura, M., Smith, J. A., & Alderman, J. (2007). Mapping School Food: A Policy Guide.

Smith, J. A. (2006). Health legislation trends in the United States of America, 2001 – 2005. New York: PAHO/WHO.

Smith. J. A. (2006). Legal Curriculum Guide in Jacobson v. Massachusetts in Public Health Law: Perspectives in 2005. Atlanta: Centers for Disease Control and Prevention, Public Health Law Program.
