---
title: "Research"
format:
    html:
        toc: true
        toc-location: right

---
My research stands at the intersection of public health, law, and climate governance, and asks the question: How can governance systems adapt to the public health implications of climate change while reducing inequities?  How can public health address the intergenerational aspects of climate change, a particularly difficult problem? Work in public health and in law has largely treated the issues of climate change as technical adaptation issues.  However, the public health challenges of the Anthropocene are governance challenges that require fundamental shifts in jurisprudence and a recognition of the significant overlap of public health and law as fields.

This area of focus is an extension of my use of population-based legal analysis in US public health law into comparative constitutional law and jurisprudence. Population-based legal analysis is an approach developed by Wendy Parmet that argues for health as a core legal value and that includes systemic perspectives of law and its impact on health. 

Public health law has lacked adequate doctrinal resources for intergenerational claims. I draw on two from the German tradition: the protective duties (_Schutzpflichten_) tradition and the German Federal Constitutional Court’s _Neubauer_ decision, which anchored intergenerational rights claims in law with the doctrine of “intertemporal guarantees of freedom,” the idea that current generations cannot act to close off the choices of future generations. In my current research, I consider the possibilities of population-based legal analysis as an approach to frame the challenges of the Anthropocene by reconceiving the carbon budget as population health and population health as not only a constitutional norm but also a possible legal anchor for intergenerational justice and public health. How can constitutional law improve and protect public health not only today but for future generations?
